apiVersion: bitnami.com/v1alpha1

kind: SealedSecret

metadata:

  creationTimestamp: null

  name: mysql-credentials

  namespace: default

spec:

  encryptedData:

    connection: AgDSQs43UU8F2X0rXSBiKdQM4WkDUutxr4geZ24WrkVsiV5bXEG7ykBFxAxeund3APtnDGPL/4bL5aapFPtobrF48p3l81l2ED4jXiu1LDLxdS8iXomWGkZSUxpDCLOvnybRtF72hNFHxVGhyH2bLVgBj7daLE7wcbt/pstj/btR1jG6zUTv1tINxHplnXPTJkTo2F3+HG8yds+lSUit+KOenTVX5T2CYCAB8WS0bnm67xEFv1/2Sz/qu3Vk3T9m8qM6+SpQRV569e4gWgcPnOk/7aYnvcorUAx/rUsdJbGKEPlHnaR9Uugu6TJ8xx4Ck3MLOvye1hESUheyq72DfWCc5e9gqxL3qu2SXYeUrmcRaJt+ZZKkql6Y5UfTMEaCYamSr+8lwrDJaru7LSYNmd2CdGX07VxWxWPGO3pzZWEw5jLK0BAGEbYJorWHrqwO3Q/vGJGm94ViJZwvr39yBzQ+cjhE4ELX3pv8yDC14ihrvz77kFADe2JH5Fjei/rkULEe+PwzRxnSRCkzUZ3zxfYVI6LL5Hmmi2EgU30xfYlIFNtsevx0SrKUJKwmMM43fdA6P/GIfF7vclSCItvQDxf0HOsD9jorJSAtJotTvcPRr03kRazd2f7MSHx8FloBSA2qbuehfEwpDZJzHgix5pSVzYaOCsrnnGccGeZ+c0XhcNT1eccLTpm6qwl2pG9TsSyvg9FWsgpIy3yuf2MpmonpYOTuvbM883TUhM0QeBxGpUM=

    password: AgAC1x87IwIrZ7wy51jZkkFr362u2ZwN6LlD+9ZLbXZ+l5Gk3sZziOTJQ45FZS9v3VBTjnQRVQutQvwqP/Oawj6utRsrRqWN6e7T5E7K63VP1sf0B6OBjyEJNiIs54Ts8V8jBfAoC+TMP1V5viPh61Lji+8M3+RviJyh/54o9et0xUhm/y6d7WNBey1vsGsKzC80P4nWVmPdVM9qHoQo+IJebRRDYKzA5kYVDYCEP2H+D9FuRCkI0r+mTDvMd8P/1u+yhf7q9DtIpOx7BNBTePo1MaRKdAcKqBszg7d13ktFFIofQ9CBmcXQMVdHp7HKGi+qsbS22xnlLmF9a6ai4skAL91QnGgppGMo6APCueyxNTxiIF2MEfFPJTMWd8zbcUx06FrjO47INOaKZouLIrJfTCB7cWiuibahbgRDKwJaoxu2VoIIdIRkUIL1VDWzNdTBqor8wVdXQn5PKBDSYGIz3xjauOcC0cR0H/VGiqh/mqCn0ksomLNvCxfLmGuxb7HZzpTXbMJgxGmhWzbCXe+/ey5lmLqiE/L2aIMf2qsqLImgwAz+St9A54MBbAwd73N07SeBpAze4UZbmDff8ZCDa+BuRqFH3xE3gW3S8mfqcdyFdvPBPk/wvXeAW5cdECdIARnXEEswJFrjWJJxGI+utP92kqAp5wCbcI6yL0mCRNDMqN+WzxTpmMSQMdElANCTnj4vvfGQJGjB5QO9Dis=

    username: AgCKcjjtocLp8Gud0xAjmKShsvpeAufEUWA7x2ZK1k+pKXizfXoJoCFyAWSiTs2HJsR20w9sEprVj1B2Lo8LnVnSrZGVxrrxvXND2TNnyAufRAhXGaIG3Ku891FTL0ihiJnVcK7s28iPyS9AO/0QDSvEWr84rmt7UZCQPAZ17ivYNQfisY/4T5VQGAE2OAv0fE9MW28yEm4AQ+mo6jSE+tzgNgZMiQ6NTYWOf1WPPxr4LRcyNyBOS899hQ1JQrtSIfGQR1+MPhwxMeQockuTspU0B5Ba0KPLGsmFrmtY4Z31/rkib4lwVg/2752rzE6XQurKYq+e9WrwcrwcIpYTwEi/aqIwL3lRRgnCrOpPymVQ5MJDfdvQ7IoEH1fTlD2m6P2ftDQJLtbTuUdiJquJ/NYjmBd+/m/mhKPeL7+Ulc3zyPT2rhZNb1ok16C4HLVtAGrPBbjcdiM9HmwnMtSZdMZh5IcmFTxvpiWaxaN9Z1oVTVbqpnh5I0ZYNG+ojv4PkxEjjivENLJtzC1MY4buEPj7AgbprluUZd9/K2HSPpEnj30j88bIP8fHYZyA+gwNMw/FMMAMtI+cazp4Si5xMj0AYhd6NCyEpk3s98Zan+1DUK0qPKWsRKX15alh3aI+PAkGeEJ3iHBtn74mCSlBrmGoAJLsSi7FOZ1p4YpFzJ5M04OWQuNspBBlXkUFEuN6rJi8wDl5iroqtNbcig==

  template:

    data: null

    metadata:

      creationTimestamp: null

      name: mysql-credentials

      namespace: default

    type: Opaque
