apiVersion: bitnami.com/v1alpha1

kind: SealedSecret

metadata:

  creationTimestamp: null

  name: paypal-cert

  namespace: default

spec:

  encryptedData:

    paypal.crt: AgBlrNnKK6bNx3G6fPDBKQb+mya81cYIubvBCayFOuW4vXztOK1eTzImvMt2Hzwm298nzUPE181rV9+shr+rhpKGTxMLwTYxPpFUwuHl0TJKdPRxL7qKinkQzPqjywwqUId/Xv0bD/unfBpMr69I2ZtNrBFTBuqbGL5pxbWx/U3n+8NQmV3njVLgu50Ah2tLinSylW/qHs6el7fUrdDemrTI02hHKYnfpCoA5pTLQ/MWkwjYf1dkuxi5KOksrXFsL4hAPaSOWMAXq6CtV04t+zwObw2hGYe5l/mf4CNsVZJAOFxTS1VoWC6NdT5yY/shGoPwvHL0/jPjp7OxeY7ub+8zEE4phJXBrFVaLZCJazOshDfS65Hb1TujjLzk8yYZo4OEjwq5BDxbMA9DBNObUR4ujZFxWaPBj/K/mTNRlYcsOXD/txJfnRf8BvRlZPpxPy0r1PFJxaaqOBbasJ5qr95HmHwy3yV7uJ1aYVq/aqO2Q7Kh9Pxpt6oLgvGGxb3wuLiSoRuZncwfUU5j3ezZRtlGK88QacTJOMuWAAjUiCXKoffZtfcH9a8uEeLlKaWJYnMGrrhHFWpoEnvG0KZrQ2X1wVWIn393+2wJlO4s4SxNl7ykxa1uChXBrgD8P5OjoVnfDLrGMIToxR86phBbsvgvyko5RXw9UaR/BkAAOKFmBj0Xj2IVydxOTmQ8Z5rUwMu9zZrOUHsA/CPI5bi8DbG/eRnyks0g+XZCZbzdNABGVHwOUanH0VRfJC5BXPx/hlKU7h5zbapc+9P4ATWUzb/DMRQfQXgrUtIWbUwaOjkrhactK1c31PW24d9xQLyNi14LL9XDvg43AbsL4pVg1n+c7fN5Q7wePim3iD+t1D9Wqh/wLGURubekhjoZT+J9Ekkk7WPLdA1hzBFdfXOwVvRvSz0lYR3EeU5ohzEkf210Cy4y/StyVRmzdgZQZCbS/72aDgGBZ+Z/nV+HjjYP+T6dTmTQaA6ZnYwSSAbnhqQowpGT6O7Ygb7ZmN+yR5FUMMHx4ALYVhM4+xPQvcLDhlYTGBJixvuMkQq+jZ4r6iSQaiOKM9Sw67vSNejm71Aaa1lc/nSR+NOm/s6lgrR8d2Pec1qDr7BA1FF4bzL/ETfwOJeAgnAIlvV/Fjw9HByrF8sF/vGKcDeRxoiRuD+/sOVSrjTyV+dYe06r+DAZZd/PJlGEp9QnpadU1/h6ARmv/LUMVlHJt89DH9Jhgs6f5ckXNgVvCqcWL4sSwYJhSuvK5TDmS16WCQKAuvb6LiU1TgUIu6qgr6dhPirQnsCuepbsEMK8QVGHKJMrNTttLoX3cXNja7Wbq6dZ5B5YjIL2gZCN9BOhN/4Ct/Ukc0dX+6QvQ552fba3TpbQbgQUI+MhOsd/veFoCJIJOOs2djnB6ALNDH5ilY9nqdjdsttXqTV97H/Le2RtQAVVxcL+GSsAU3WEoyZIkSs5tlRyc87DKUnWaxiIq5AKWsp+RSih5IK+PwP0WNzxHn7lSe402qzRCHOQ5m+Ig0NUk2vqVRv+WqTiDzZa6qnwxnbUPct0sFurbIfin9AfD5H/eOuchdwvKkYwlC4okAJaq9taj7BwSjA6D2rrt23xU+vqETaApQMa2NqxGtv3K6G9o/UzHgh3ICn6lWC2Tj3NYd6Qr1U7U4cUbc5vqLM/jj8Nuj98gwN6D5D0hRJmrUJvCgORDOZTixP5hJ/u8YfM572jbx9metdpuAWcjXv6+oMH3VAu51mgXNX/m8b/XRtWMfgCWm12rjsVJj7ZjBp9qc0fkkduaK60R3HZzIb+c2Qm56bWCuzIbvWLxaKjf8EU+ljnZRa6UVu3tc+B0i42yHH4SL2CTZM3UnF9DaE/IHeQICYNi+9l7sZy6gqrfcK+1MKauGKpno2IDh9j/eChPdgor9O26BethVPS2zDNl+NxPd9oRYD/5VrxS6T9J05GOKeUceJViWCExp8CQ6JU8uC9pU4vt8+eBknlgiePnAKjRi/ZCw0YSnZhnJOqlgGeFe2DjtVYalryZz1FZLI8/Cr1yebpeAmXoh/8HVjr0DHIkPGj8hrFzGj0Frwxq7eAef4Rr7/BwrQv

  template:

    data: null

    metadata:

      creationTimestamp: null

      name: paypal-cert

      namespace: default

    type: Opaque
